CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(200) NOT NULL,
  password VARCHAR(200)  NOT NULL,
  UNIQUE (email)
);

CREATE TABLE files (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  filename VARCHAR(150) NOT NULL,
  size INTEGER NOT NULL,
  mimetype VARCHAR(100) NOT NULL,
  timeStamp VARCHAR(255) NOT NULL,
  uniqueFileNamePath VARCHAR(255) NOT NULL,
  userId INTEGER REFERENCES users(Id)
);